### ISSUE TITLE
源码部署后密码是什么？不是admin!Aa2020？

### ISSUE THREAD

**Issue by sadbosan** [creditease-sec/insight2#13]
admin/admin!Aa2020  一直报用户名密码错误

**Comment by sadbosan** [comment]
密码加密方式是什么  我自己写个md5密码  还是不行

**Comment by CESRC-CreditEase** [comment]
python run.py --init=db可以初始化数据库用户名密码（admin/admin!Aa2020）
logic/util.py 有密码加密函数password_md5
