### ISSUE TITLE
看到requirements中有cas_client，这是支持cas了吗？

### ISSUE THREAD

**Issue by T4di5** [creditease-sec/insight2#15]
rt

**Comment by CESRC-CreditEase** [comment]
内部版本已扩展实现，未来的版本会根据社区的需求整理发布，现有版本在前后端有预留接口，也可自行实现，感谢支持

**Comment by T4di5** [comment]
> 版本

现有的2.0.2版本吗？在后端就看到个cas_client，前端就直接没看到，预留端接口在哪呢？

**Comment by CESRC-CreditEase** [comment]
当前版本： 

- 后端需要实现CAS回调接口,也就是验签相关过程，
`href` 字段需要在`AuthMode`表中的`config`字段以JSON方式存储，详见 [代码](https://github.com/creditease-sec/insight2/blob/aa80e1c7d15f0beeeebface2811ad8b075a82691/action/authmode.py#L71)中实现过程 
- 前端的预留是
后端`api/authmode/all`接口中可返回href字段，前端判断，如果href不为空会跳转到href的地址，也就是CAS的登录页面。
相关 [前端逻辑代码](https://github.com/creditease-sec/insight2_front/blob/663039f0c38ebf821df609521f0e941544332602/src/components/page/Login.vue#L102)

说是预留接口确实有点牵强了，应该说是预留了个可供实现的方式。

**Comment by soldier3r** [comment]
改了出很多问题，能开源这个功能吗？

**Comment by T4di5** [comment]
> 改了出很多问题，能开源这个功能吗？

预留了接口，可以直接去改
