### ISSUE TITLE
大佬前后端分离，上传文件是404了，docker镜像里也是这样

### ISSUE THREAD

**Issue by T4di5** [creditease-sec/insight2#17]
rt

**Comment by CESRC-CreditEase** [comment]
检查下反向代理的配置 参考 [https://github.com/creditease-sec/insight2_front/blob/master/production_nginx.conf](https://github.com/creditease-sec/insight2_front/blob/master/production_nginx.conf)

由于后端版本的变动更新，注意/api 和 /upload (如果是404，查看下url中 `upload`是否为`static`,如果是，把`/upload`替换为`/static`)

**Comment by CESRC-CreditEase** [comment]
最新版本中已将`/upload`替换为`/static`
