### ISSUE TITLE
“编辑漏洞” 中，漏洞证明 和 解决方案 有bug

### ISSUE THREAD

**Issue by MarkHappyShao** [creditease-sec/insight2#19]
“编辑漏洞” 中，漏洞证明 和 解决方案  编写完后， 点击漏洞查看，“解决方案”显示“无”，点击跳转至“文章”；  编写的解决方案内容 显示在了 漏洞证明内容的最下面了。

**Comment by CESRC-CreditEase** [comment]
点击`漏洞查看`，`解决方案`已改为`关联方案` ，此处如果在`新增漏洞`关联了解决方案`文章`，会显示`文章标题`，点击跳转，如未关联将不会显示`无`，以造成误导，感谢支持。
