### ISSUE TITLE
老是提示验证码错误，正确了也提示

### ISSUE THREAD

**Issue by Chillimeat** [creditease-sec/insight2#2]
老是提示验证码错误，正确了也提示

**Comment by CESRC-CreditEase** [comment]
试下重新启动服务，看看日志有什么错误信息，可能是服务没正常启动

**Comment by Chillimeat** [comment]
重新试了，还是不行，贴上日志吧
Attaching to insight2_docker_web_mysql_1, insight2_docker_web_redis_1, insight2_docker_backend_1, insight2_docker_front_1
web_mysql_1  | 2020-06-03 10:03:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.30-1debian10 started.
web_mysql_1  | 2020-06-03 10:03:17+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
web_mysql_1  | 2020-06-03 10:03:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.30-1debian10 started.
web_mysql_1  | 2020-06-03T10:03:17.841922Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
web_mysql_1  | 2020-06-03T10:03:17.842858Z 0 [Note] mysqld (mysqld 5.7.30) starting as process 1 ...
web_mysql_1  | 2020-06-03T10:03:17.844931Z 0 [Note] InnoDB: PUNCH HOLE support available
web_mysql_1  | 2020-06-03T10:03:17.844942Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
web_mysql_1  | 2020-06-03T10:03:17.844944Z 0 [Note] InnoDB: Uses event mutexes
web_mysql_1  | 2020-06-03T10:03:17.844946Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
web_mysql_1  | 2020-06-03T10:03:17.844948Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
web_mysql_1  | 2020-06-03T10:03:17.844950Z 0 [Note] InnoDB: Using Linux native AIO
web_mysql_1  | 2020-06-03T10:03:17.845143Z 0 [Note] InnoDB: Number of pools: 1
web_mysql_1  | 2020-06-03T10:03:17.845243Z 0 [Note] InnoDB: Using CPU crc32 instructions
web_mysql_1  | 2020-06-03T10:03:17.846464Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
web_mysql_1  | 2020-06-03T10:03:17.850844Z 0 [Note] InnoDB: Completed initialization of buffer pool
web_mysql_1  | 2020-06-03T10:03:17.858649Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
web_mysql_1  | 2020-06-03T10:03:17.880560Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
web_mysql_1  | 2020-06-03T10:03:17.975904Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
web_mysql_1  | 2020-06-03T10:03:17.975979Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
web_mysql_1  | 2020-06-03T10:03:18.029918Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
web_mysql_1  | 2020-06-03T10:03:18.030554Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
web_mysql_1  | 2020-06-03T10:03:18.030562Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
web_mysql_1  | 2020-06-03T10:03:18.030757Z 0 [Note] InnoDB: Waiting for purge to start
web_mysql_1  | 2020-06-03T10:03:18.082943Z 0 [Note] InnoDB: 5.7.30 started; log sequence number 12635368
web_mysql_1  | 2020-06-03T10:03:18.083262Z 0 [Note] Plugin 'FEDERATED' is disabled.
web_mysql_1  | 2020-06-03T10:03:18.094330Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
web_mysql_1  | 2020-06-03T10:03:18.124205Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
web_mysql_1  | 2020-06-03T10:03:18.124221Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
web_mysql_1  | 2020-06-03T10:03:18.125264Z 0 [Warning] CA certificate ca.pem is self signed.
web_mysql_1  | 2020-06-03T10:03:18.125321Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
web_mysql_1  | 2020-06-03T10:03:18.126070Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
web_mysql_1  | 2020-06-03T10:03:18.126166Z 0 [Note] IPv6 is available.
web_mysql_1  | 2020-06-03T10:03:18.126176Z 0 [Note]   - '::' resolves to '::';
web_mysql_1  | 2020-06-03T10:03:18.126189Z 0 [Note] Server socket created on IP: '::'.
web_mysql_1  | 2020-06-03T10:03:18.150640Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200603 10:03:18
web_mysql_1  | 2020-06-03T10:03:18.157268Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
web_mysql_1  | 2020-06-03T10:03:18.188680Z 0 [Note] Event Scheduler: Loaded 0 events
web_mysql_1  | 2020-06-03T10:03:18.188786Z 0 [Note] mysqld: ready for connections.
web_mysql_1  | Version: '5.7.30'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
web_redis_1  | 1:C 03 Jun 2020 10:03:17.319 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
web_redis_1  | 1:C 03 Jun 2020 10:03:17.319 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
web_redis_1  | 1:C 03 Jun 2020 10:03:17.319 # Configuration loaded
web_redis_1  | 1:M 03 Jun 2020 10:03:17.331 * Running mode=standalone, port=6379.
web_redis_1  | 1:M 03 Jun 2020 10:03:17.332 # Server initialized
web_redis_1  | 1:M 03 Jun 2020 10:03:17.332 * Ready to accept connections

**Comment by Chillimeat** [comment]
> 试下重新启动服务，看看日志有什么错误信息，可能是服务没正常启动
重新试了，还是不行，贴上日志吧
Attaching to insight2_docker_web_mysql_1, insight2_docker_web_redis_1, insight2_docker_backend_1, insight2_docker_front_1
web_mysql_1 | 2020-06-03 10:03:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.30-1debian10 started.
web_mysql_1 | 2020-06-03 10:03:17+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
web_mysql_1 | 2020-06-03 10:03:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.30-1debian10 started.
web_mysql_1 | 2020-06-03T10:03:17.841922Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
web_mysql_1 | 2020-06-03T10:03:17.842858Z 0 [Note] mysqld (mysqld 5.7.30) starting as process 1 ...
web_mysql_1 | 2020-06-03T10:03:17.844931Z 0 [Note] InnoDB: PUNCH HOLE support available
web_mysql_1 | 2020-06-03T10:03:17.844942Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
web_mysql_1 | 2020-06-03T10:03:17.844944Z 0 [Note] InnoDB: Uses event mutexes
web_mysql_1 | 2020-06-03T10:03:17.844946Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
web_mysql_1 | 2020-06-03T10:03:17.844948Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
web_mysql_1 | 2020-06-03T10:03:17.844950Z 0 [Note] InnoDB: Using Linux native AIO
web_mysql_1 | 2020-06-03T10:03:17.845143Z 0 [Note] InnoDB: Number of pools: 1
web_mysql_1 | 2020-06-03T10:03:17.845243Z 0 [Note] InnoDB: Using CPU crc32 instructions
web_mysql_1 | 2020-06-03T10:03:17.846464Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
web_mysql_1 | 2020-06-03T10:03:17.850844Z 0 [Note] InnoDB: Completed initialization of buffer pool
web_mysql_1 | 2020-06-03T10:03:17.858649Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
web_mysql_1 | 2020-06-03T10:03:17.880560Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
web_mysql_1 | 2020-06-03T10:03:17.975904Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
web_mysql_1 | 2020-06-03T10:03:17.975979Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
web_mysql_1 | 2020-06-03T10:03:18.029918Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
web_mysql_1 | 2020-06-03T10:03:18.030554Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
web_mysql_1 | 2020-06-03T10:03:18.030562Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
web_mysql_1 | 2020-06-03T10:03:18.030757Z 0 [Note] InnoDB: Waiting for purge to start
web_mysql_1 | 2020-06-03T10:03:18.082943Z 0 [Note] InnoDB: 5.7.30 started; log sequence number 12635368
web_mysql_1 | 2020-06-03T10:03:18.083262Z 0 [Note] Plugin 'FEDERATED' is disabled.
web_mysql_1 | 2020-06-03T10:03:18.094330Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
web_mysql_1 | 2020-06-03T10:03:18.124205Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
web_mysql_1 | 2020-06-03T10:03:18.124221Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
web_mysql_1 | 2020-06-03T10:03:18.125264Z 0 [Warning] CA certificate ca.pem is self signed.
web_mysql_1 | 2020-06-03T10:03:18.125321Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
web_mysql_1 | 2020-06-03T10:03:18.126070Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
web_mysql_1 | 2020-06-03T10:03:18.126166Z 0 [Note] IPv6 is available.
web_mysql_1 | 2020-06-03T10:03:18.126176Z 0 [Note] - '::' resolves to '::';
web_mysql_1 | 2020-06-03T10:03:18.126189Z 0 [Note] Server socket created on IP: '::'.
web_mysql_1 | 2020-06-03T10:03:18.150640Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200603 10:03:18
web_mysql_1 | 2020-06-03T10:03:18.157268Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
web_mysql_1 | 2020-06-03T10:03:18.188680Z 0 [Note] Event Scheduler: Loaded 0 events
web_mysql_1 | 2020-06-03T10:03:18.188786Z 0 [Note] mysqld: ready for connections.
web_mysql_1 | Version: '5.7.30' socket: '/var/run/mysqld/mysqld.sock' port: 3306 MySQL Community Server (GPL)
web_redis_1 | 1:C 03 Jun 2020 10:03:17.319 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
web_redis_1 | 1:C 03 Jun 2020 10:03:17.319 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
web_redis_1 | 1:C 03 Jun 2020 10:03:17.319 # Configuration loaded
web_redis_1 | 1:M 03 Jun 2020 10:03:17.331 * Running mode=standalone, port=6379.
web_redis_1 | 1:M 03 Jun 2020 10:03:17.332 # Server initialized
web_redis_1 | 1:M 03 Jun 2020 10:03:17.332 * Ready to accept connections

**Comment by ShuailingMa** [comment]
应该是用户名不存在，或者用户名或者密码错误，出现这些情况，好像也会说验证码错误
