### ISSUE TITLE
反馈bug

### ISSUE THREAD

**Issue by soldier3r** [creditease-sec/insight2#26]
![image](https://user-images.githubusercontent.com/48548866/98621038-64727080-2341-11eb-9da5-a82af13dde83.png)
导入的数据库是一致的，登陆就显示账户密码错误，这种是什么问题？
我用docker也是这个问题，能拉入群吗？公众号没有人拉。

反馈个小问题：数据库配置文件缺少USE insight2;

**Comment by soldier3r** [comment]
python run.py --init=db

**Comment by soldier3r** [comment]
作者回答了：python run.py --init=db

**Comment by soldier3r** [comment]
修改密码处报错：
Non-ASCII character '\xe6' in file /home/insight2/logic/password_judge.py on line 6, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details (password_judge.py, line 6)
password_judge.py头增加#encoding:utf-8

**Comment by CESRC-CreditEase** [comment]
源代码部署请使用python3.7 +

**Comment by soldier3r** [comment]
好的，有交流群吗？

**Comment by CESRC-CreditEase** [comment]
如果使用docker一键部署请参考 [https://github.com/creditease-sec/insight2_docker](https://github.com/creditease-sec/insight2_docker)

源代码部署项目
可以需要自行修改配置文件settings.py 配置数据库，redis地址
python run.py --init=db 初始化数据库
python run.py启动

**Comment by CESRC-CreditEase** [comment]
![Uploading 2088087525.jpg…]()

**Comment by CESRC-CreditEase** [comment]
![2088087525](https://user-images.githubusercontent.com/37574065/98642338-45d3a000-2368-11eb-8d08-ed92e2aa0a74.jpg)
