### ISSUE TITLE
[bug] 安全测试功能返回接口错误，无法调用扩展

### ISSUE THREAD

**Issue by ivybao0628** [creditease-sec/insight2#30]
![企业微信20210120-211312](https://user-images.githubusercontent.com/13583188/105179593-7acc5200-5b64-11eb-9c77-6aec1a6cdd9b.png)
 调用的是/api/extension/run 这个接口 但返回方法不支持或接口不存在，查看了代码里也没有此接口
![企业微信20210120-211548](https://user-images.githubusercontent.com/13583188/105179784-b1a26800-5b64-11eb-84c4-c777330a6c3f.png)

**Comment by CESRC-CreditEase** [comment]
此功能需要自行编写扩展实现,可参考 [https://cesrc-creditease.github.io/doc/chapter4/section6.html](https://cesrc-creditease.github.io/doc/chapter4/section6.html),  感谢支持!
