### ISSUE TITLE
真的不开源的吗？

### ISSUE THREAD

**Issue by T4di5** [creditease-sec/insight2#6]
真的不开源的吗？

**Comment by CESRC-CreditEase** [comment]
开源，Docker镜像里有源码的，只不过为了更加便于修改和阅读，正在整理代码中，没放到Github上来，敬请期待。

**Comment by T4di5** [comment]
> 开源，Docker镜像里有源码的，只不过为了更加便于修改和阅读，正在整理代码中，没放到Github上来，敬请期待。

主要是只有镜像，没有源码，不方便安全自查，自己打成镜像更放心一些

**Comment by cor0ps** [comment]
希望开源

**Comment by T4di5** [comment]
不开源了
