### ISSUE TITLE
无法进行升级到2.03

### ISSUE THREAD

**Issue by zwf8558** [creditease-sec/insight2#9]
当前版本 2.0.1
2.0.3
New features
报告生成扩展 生成每日风险处理报告，发送邮件
计划任务管理
计划任务数据备份
唯一用户在线
URL加入过滤参数，保证刷新后页面不变

**Comment by CESRC-CreditEase** [comment]
版本计划有变 ，当前最新版本为2.0.2 ，可通过Docker-compose或源码进行升级，感谢支持
